export type Service = {
  id: string;
  slug: string;
  name: string;
  category: string;
  price: number;
  priceLabel: string;
  description: string;
  details: string[];
  badge?: string;
  icon: string;
};

export const CATEGORIES = ["All", "Design", "Web Development", "Marketing", "Photography", "Google My Business"];

export const SERVICES: Service[] = [
  {
    id: "1",
    slug: "business-card-design",
    name: "Business Card Design",
    category: "Design",
    price: 500,
    priceLabel: "₨ 500",
    description: "Professional, print-ready business card in 24 hrs",
    details: [
      "2 unique concepts",
      "Unlimited revisions",
      "Print-ready PDF + source file",
      "Delivered in 24 hours",
    ],
    badge: "Best Seller",
    icon: "id-card",
  },
  {
    id: "2",
    slug: "logo-design",
    name: "Logo Design",
    category: "Design",
    price: 1500,
    priceLabel: "₨ 1,500",
    description: "Unique vector logo with unlimited revisions",
    details: [
      "3 initial concepts",
      "Unlimited revisions",
      "Vector files (AI, SVG, PNG)",
      "Brand color palette included",
    ],
    icon: "star",
  },
  {
    id: "3",
    slug: "facebook-ad-banner",
    name: "Facebook Ad Banner",
    category: "Design",
    price: 200,
    priceLabel: "₨ 200",
    description: "Eye-catching Facebook ad banner designed to convert",
    details: [
      "Optimized dimensions",
      "2 revisions",
      "PNG + editable file",
      "24-hour delivery",
    ],
    icon: "image",
  },
  {
    id: "4",
    slug: "mobile-app-ui",
    name: "Mobile App UI/UX",
    category: "Design",
    price: 8000,
    priceLabel: "₨ 8,000",
    description: "Clean, modern mobile app screen designs",
    details: [
      "Up to 5 screens",
      "Figma source file",
      "User flow included",
      "3-day delivery",
    ],
    icon: "mobile",
  },
  {
    id: "5",
    slug: "landing-page",
    name: "Landing Page",
    category: "Web Development",
    price: 8000,
    priceLabel: "₨ 8,000",
    description: "Conversion-focused single-page website",
    details: [
      "Responsive design",
      "Contact form integration",
      "SEO-ready structure",
      "5-day delivery",
    ],
    badge: "Popular",
    icon: "laptop-code",
  },
  {
    id: "6",
    slug: "corporate-website",
    name: "Corporate Website",
    category: "Web Development",
    price: 25000,
    priceLabel: "₨ 25,000",
    description: "Multi-page professional site with contact form",
    details: [
      "Up to 6 pages",
      "WordPress CMS",
      "Mobile responsive",
      "7-day delivery",
    ],
    icon: "building",
  },
  {
    id: "7",
    slug: "ecommerce-store",
    name: "E-Commerce Store",
    category: "Web Development",
    price: 45000,
    priceLabel: "₨ 45,000",
    description: "Full online store with product management and payments",
    details: [
      "WooCommerce setup",
      "Up to 20 products",
      "Payment gateway integration",
      "10-day delivery",
    ],
    badge: "Premium",
    icon: "store",
  },
  {
    id: "8",
    slug: "seo-optimization",
    name: "SEO Optimization",
    category: "Marketing",
    price: 3000,
    priceLabel: "₨ 3,000",
    description: "Rank higher on Google with on-page SEO setup",
    details: [
      "Keyword research",
      "Meta tags optimization",
      "Site speed check",
      "Monthly report",
    ],
    icon: "search",
  },
  {
    id: "9",
    slug: "social-media-management",
    name: "Social Media Management",
    category: "Marketing",
    price: 5000,
    priceLabel: "₨ 5,000 /mo",
    description: "Monthly content creation and posting (1 platform)",
    details: [
      "12 posts per month",
      "Custom graphics",
      "Caption copywriting",
      "Basic analytics",
    ],
    icon: "share-alt",
  },
  {
    id: "10",
    slug: "email-automation",
    name: "Email Automation Setup",
    category: "Marketing",
    price: 4000,
    priceLabel: "₨ 4,000",
    description: "Automated email sequences to nurture your leads",
    details: [
      "Welcome email series",
      "Mailchimp or Brevo setup",
      "3 automated sequences",
      "List import help",
    ],
    icon: "envelope",
  },
  {
    id: "11",
    slug: "product-photography",
    name: "Product Photography",
    category: "Photography",
    price: 4000,
    priceLabel: "₨ 4,000",
    description: "Professional product shoot (up to 10 photos)",
    details: [
      "Up to 10 products",
      "White background + lifestyle shots",
      "Edited high-res JPEGs",
      "2-day turnaround",
    ],
    icon: "camera",
  },
  {
    id: "12",
    slug: "google-my-business",
    name: "Google My Business Setup",
    category: "Google My Business",
    price: 2000,
    priceLabel: "₨ 2,000",
    description: "Full GMB profile creation and optimization",
    details: [
      "Profile creation & verification",
      "Business info optimization",
      "Photo upload",
      "Review response setup",
    ],
    icon: "map-marker-alt",
  },
  {
    id: "13",
    slug: "brochure-flyer-design",
    name: "Brochure / Flyer Design",
    category: "Design",
    price: 700,
    priceLabel: "₨ 700",
    description: "Print-ready brochure or flyer design in 24 hrs",
    details: [
      "Single or double-sided",
      "3 revisions included",
      "Print-ready PDF + source file",
      "24-hour delivery",
    ],
    icon: "file-text",
  },
  {
    id: "14",
    slug: "google-ads-campaign",
    name: "Google Ads Campaign",
    category: "Marketing",
    price: 8000,
    priceLabel: "₨ 8,000",
    description: "Targeted Google Ads setup to drive paying customers",
    details: [
      "Keyword research & targeting",
      "Ad copy writing",
      "Campaign structure setup",
      "30-day performance monitoring",
    ],
    badge: "Popular",
    icon: "trending-up",
  },
  {
    id: "15",
    slug: "website-maintenance",
    name: "Website Maintenance",
    category: "Web Development",
    price: 3000,
    priceLabel: "₨ 3,000 /mo",
    description: "Monthly updates, backups, and speed optimization",
    details: [
      "Content & plugin updates",
      "Weekly automated backups",
      "Security monitoring",
      "Speed & uptime checks",
    ],
    icon: "settings",
  },
  {
    id: "16",
    slug: "pitch-deck-design",
    name: "Pitch Deck Design",
    category: "Design",
    price: 2500,
    priceLabel: "₨ 2,500",
    description: "Professional investor-ready presentation in 48 hrs",
    details: [
      "Up to 15 slides",
      "Custom graphics & icons",
      "PowerPoint + PDF delivery",
      "2 revisions included",
    ],
    icon: "monitor",
  },
  {
    id: "17",
    slug: "whatsapp-business-setup",
    name: "WhatsApp Business Setup",
    category: "Marketing",
    price: 1500,
    priceLabel: "₨ 1,500",
    description: "Full WhatsApp Business profile + product catalog setup",
    details: [
      "Business profile optimization",
      "Product catalog creation",
      "Auto-reply messages setup",
      "Quick replies & labels",
    ],
    badge: "New",
    icon: "message-circle",
  },
  {
    id: "18",
    slug: "social-media-profile-setup",
    name: "Social Media Profile Setup",
    category: "Marketing",
    price: 2000,
    priceLabel: "₨ 2,000",
    description: "Fully optimized profiles across Facebook, Instagram & LinkedIn",
    details: [
      "Profile & cover design",
      "Bio & keyword optimization",
      "Highlights & pinned post setup",
      "Up to 3 platforms",
    ],
    icon: "users",
  },
  {
    id: "19",
    slug: "reels-short-video-editing",
    name: "Reels & Short Video Editing",
    category: "Marketing",
    price: 2500,
    priceLabel: "₨ 2,500",
    description: "Scroll-stopping Reels & TikTok edits that grow your audience fast",
    details: [
      "Up to 5 short videos",
      "Captions & subtitles included",
      "Trending audio & transitions",
      "3-day delivery",
    ],
    badge: "Trending",
    icon: "trending-up",
  },
];
